# Generated by Django 4.2.11 on 2024-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_donors_city_id_remove_donors_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='city_iso2',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AddField(
            model_name='donors',
            name='state_iso2',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
