# Generated by Django 4.2.11 on 2024-04-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donors_city_iso2_donors_state_iso2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='city_iso2',
        ),
    ]
