# Generated by Django 4.2.11 on 2024-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_donations_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='donations',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
