IN_STATES = [
    {'id': 4017, 'name': 'Andhra Pradesh', 'iso2': 'AP'},
    {'id': 4024, 'name': 'Arunachal Pradesh', 'iso2': 'AR'},
    {'id': 4027, 'name': 'Assam', 'iso2': 'AS'},
    {'id': 4037, 'name': 'Bihar', 'iso2': 'BR'},
    {'id': 4031, 'name': 'Chandigarh', 'iso2': 'CH'},
    {'id': 4040, 'name': 'Chhattisgarh', 'iso2': 'CT'},
    {'id': 4021, 'name': 'Delhi', 'iso2': 'DL'},
    {'id': 4009, 'name': 'Goa', 'iso2': 'GA'},
    {'id': 4030, 'name': 'Gujarat', 'iso2': 'GJ'},
    {'id': 4007, 'name': 'Haryana', 'iso2': 'HR'},
    {'id': 4020, 'name': 'Himachal Pradesh', 'iso2': 'HP'},
    {'id': 4029, 'name': 'Jammu and Kashmir', 'iso2': 'JK'},
    {'id': 4025, 'name': 'Jharkhand', 'iso2': 'JH'},
    {'id': 4026, 'name': 'Karnataka', 'iso2': 'KA'},
    {'id': 4028, 'name': 'Kerala', 'iso2': 'KL'},
    {'id': 4852, 'name': 'Ladakh', 'iso2': 'LA'},
    {'id': 4019, 'name': 'Lakshadweep', 'iso2': 'LD'},
    {'id': 4039, 'name': 'Madhya Pradesh', 'iso2': 'MP'},
    {'id': 4008, 'name': 'Maharashtra', 'iso2': 'MH'},
    {'id': 4010, 'name': 'Manipur', 'iso2': 'MN'},
    {'id': 4006, 'name': 'Meghalaya', 'iso2': 'ML'},
    {'id': 4036, 'name': 'Mizoram', 'iso2': 'MZ'},
    {'id': 4018, 'name': 'Nagaland', 'iso2': 'NL'},
    {'id': 4013, 'name': 'Odisha', 'iso2': 'OR'},
    {'id': 4011, 'name': 'Puducherry', 'iso2': 'PY'},
    {'id': 4015, 'name': 'Punjab', 'iso2': 'PB'},
    {'id': 4014, 'name': 'Rajasthan', 'iso2': 'RJ'},
    {'id': 4034, 'name': 'Sikkim', 'iso2': 'SK'},
    {'id': 4035, 'name': 'Tamil Nadu', 'iso2': 'TN'},
    {'id': 4012, 'name': 'Telangana', 'iso2': 'TG'},
    {'id': 4038, 'name': 'Tripura', 'iso2': 'TR'},
    {'id': 4022, 'name': 'Uttar Pradesh', 'iso2': 'UP'},
    {'id': 4016, 'name': 'Uttarakhand', 'iso2': 'UT'},
    {'id': 4853, 'name': 'West Bengal', 'iso2': 'WB'}
]


QUOTES = [
    {"quote": "The measure of a life, after all, is not its duration, but its donation.",
        "author": "Corrie ten Boom"},
    {"quote": "The smallest act of kindness is worth more than the grandest intention.",
        "author": "Oscar Wilde"},
    {"quote": "No one has ever become poor by giving.", "author": "Anne Frank"},
    {"quote": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", "author": "Ralph Waldo Emerson"},
    {"quote": "When we give cheerfully and accept gratefully, everyone is blessed.",
        "author": "Maya Angelou"},
    {"quote": "You have not lived today until you have done something for someone who can never repay you.",
        "author": "John Bunyan"},
    {"quote": "We make a living by what we get, but we make a life by what we give.",
        "author": "Winston Churchill"},
    {"quote": "The meaning of life is to find your gift. The purpose of life is to give it away.",
        "author": "Pablo Picasso"},
    {"quote": "Generosity is the most natural outward expression of an inner attitude of compassion and loving-kindness.", "author": "Dalai Lama"},
    {"quote": "The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own.", "author": "Lao Tzu"},
    {"quote": "We rise by lifting others.", "author": "Robert Ingersoll"},
    {"quote": "Happiness doesn't result from what we get, but from what we give.",
        "author": "Ben Carson"},
    {"quote": "The best way to find yourself is to lose yourself in the service of others.",
        "author": "Mahatma Gandhi"},
    {"quote": "Service to others is the rent you pay for your room here on Earth.",
        "author": "Muhammad Ali"},
    {"quote": "To do more for the world than the world does for you, that is success.",
        "author": "Henry Ford"},
    {"quote": "One of the greatest feelings in the world is knowing that we as individuals can make a difference.",
        "author": "Jackie Chan"},
    {"quote": "Don't wait for other people to be loving, giving, compassionate, grateful, forgiving, generous, or friendly... lead the way!", "author": "Steve Maraboli"},
    {"quote": "The only gift is a portion of thyself.",
        "author": "Ralph Waldo Emerson"},
    {"quote": "Charity sees the need, not the cause.", "author": "German Proverb"},
    {"quote": "There is no exercise better for the heart than reaching down and lifting people up.",
        "author": "John Holmes"},
    {"quote": "We can't help everyone, but everyone can help someone.",
        "author": "Ronald Reagan"},
    {"quote": "Kindness is the language which the deaf can hear and the blind can see.",
        "author": "Mark Twain"},
    {"quote": "Giving is not just about making a donation. It is about making a difference.",
        "author": "Kathy Calvin"},
    {"quote": "What we do for ourselves dies with us. What we do for others and the world remains and is immortal.",
        "author": "Albert Pine"},
    {"quote": "The world is changed by your example, not your opinion.",
        "author": "Paulo Coelho"}
]
